### ISSUE TITLE
New page doesn't show sidebar block

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1036]
Pages that I built before the latest sandbox update still show the light blue sidebar block, but new pages aren't showing the block even though it's been built the same way.:
https://live-ucbdev-homepage.pantheonsite.io/academics/bs-aerospace-engineering

![Screenshot 2024-06-05 at 2 01 23 PM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/6dec7d14-9e85-4a28-a240-e3f250f5a34e)

New page:
https://live-ucbdev-homepage.pantheonsite.io/academics/ba-environmental-studies
![Screenshot 2024-06-05 at 2 02 24 PM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/873c702d-1b98-44fa-a86f-72e35c868154)

![Screenshot 2024-06-05 at 2 02 34 PM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/92f75bb4-df97-4479-b5d2-37d9b784ccff)

**Comment by jcsparks** [comment]
Hey @wturnbull - looks like you picked a `Tag Cloud` block instead of, what I suspect was supposed to be a `Text Block` on the one that isn't working.  I think if you create a `Text block` instead it should work as expected. 

![Screenshot 2024-06-06 at 9 14 58 AM](https://github.com/CuBoulder/tiamat-theme/assets/12704433/1d0a8c28-434b-431a-8b6e-23c3670294d4)

Here's the one that's working

![Screenshot 2024-06-06 at 9 15 11 AM](https://github.com/CuBoulder/tiamat-theme/assets/12704433/f22959a3-1ea6-4188-811f-61dffbae8a15)

**Comment by wturnbull** [comment]
So sorry to add extra work for user error! Thank you so much for for looking into this.

**Comment by jcsparks** [comment]
no problem
