### ISSUE TITLE
Header styles clean up

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#1050]
Some of the headers look like they're not set consistently with how it was in D7.  

The `H2` for example is ~52px in D10 and was more like 32px in D7.  

Should confer with @kevincrafts and nail down the exact font sizes for all of the Headers.

**Comment by nicolewaldrip** [comment]
@kevincrafts  and @jcsparks  I've also been noticing that it's not consistent with D7 of when we're using the condensed version of roboto vs. the regular (non-condensed version) across the header styles. Not sure if that was an intentional change in D10? If not, is that going to be addressed with this ticket? Not sure where you are in the process with this one, so happy to log another ticket if it needs something separate.

**Comment by jnicholCU** [comment]
@nicolewaldrip I'm working on this ticket right now. We had discussed the different versions of Roboto last week and made the decision to have it different from D7 for now. Kevin and Jeremy can probably give more info but it was an intentional choice at this time.
