### ISSUE TITLE
Privacy Statement link in footer

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1093]
The Privacy Statement link in the branded section of the footer on /chancellor should link to /about/privacy-statement but it links to /compliance instead. I'm guessing this will be an issue on all D10 sites… (just noticed it on the new express site as well.)

**Comment by timurtripp** [comment]
The link is already linking to `/about/privacy-statement` (see bottom-left of screenshot as I hover over the link), it looks like there is a redirect happening from `/about/privacy-statement` to `/compliance`. This is an issue on D7 sites as well.
<img width="868" alt="Screenshot 2024-07-15 at 9 20 07 AM" src="https://github.com/user-attachments/assets/51d42fb7-710f-4fc2-9d32-5a7d277413ec">

**Comment by jcsparks** [comment]
We're going to go ahead and skip the redirect, make the Privacy link go directly `/compliance`

**Comment by asvensen** [comment]
The Privacy link in all footers needs to link to /about/privacy-statement. /compliance is the wrong place to link to.

**Comment by jcsparks** [comment]
Okay, we'll make it so.

**Comment by asvensen** [comment]
Hi @jcsparks! I see this has been closed. Has the fix been pushed out?

**Comment by jcsparks** [comment]
@asvensen - the ticket has been closed because the developers have completed their part of the process and the changes have been merged into the codebase.  

It's not live for you yet because we roll out updates periodically that include all of the changes that have been merged in since the last update.  You can expect to see this next time we do updates for the sites.

**Comment by asvensen** [comment]
Makes total sense! Thank you.
