### ISSUE TITLE
Faculty Publications Feed

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1146]
One of the last features developed for D7 Web Express was a feed of faculty publications from experts.colorado.edu. I think there's a somewhat limited use (27 sites) of this feature on sites, and required someone from the Web Express team to enable.

The blocks have a number of filters including:

- Publication date range
- Department ID or Name (in experts)
- Faculty Email Address

The filters also allow the ability to use existing persons on the site and use the emails associated with them in part of the api call.

The display options include:

- Number of results per page (all, 25, 50, 100)
- Sort (new to old, old to new)

Example links
https://www.colorado.edu/instaar/scott-taylor#publications-537
https://www.colorado.edu/instaar/tom-marchitto#publications-255

**Comment by kevincrafts** [comment]
Got this note from INSTAAR....

Regarding development of faculty publications for Drupal 10... I should let you know that INSTAAR would be happy to be a guinea pig. And if y'all are still in the early stages of development, we also would really like to offer ideas for a new-and-improved format. Multiple faculty really want a different, more conventional, and easier-to-skim listing for each publication. Maybe the new format could be a second option instead of replacing the current one? Anyhow, just let me know when y'all might be ready for feedback and I'll send suggestions. And when you have any kind of rough timeline, we would appreciate that too.

**Comment by timurtripp** [comment]
Context is going away so we need to discuss how to implement this going forward. @AlanBCole said he'll work on gathering some data about its use in D7.

Changing the format of how articles are displayed is something we can do, however since the D10 version will be a complete rewrite there won't be both an old and new format available – old is going away completely.

Most likely the settings for these won't migrate automatically and will need to be set up again post migration. Not able to provide a timeline yet as we still need more information.
