### ISSUE TITLE
Page with sidebar horizontal scrollbar on mobile

### ISSUE THREAD

**Issue by timurtripp** [CuBoulder/tiamat-theme#1198]
Browsing [Library News](https://libraries.colorado.edu/news-events/library-news) on my phone and I'm getting an unnecessary horizontal scrollbar. This looks to be a result of the page having a right-side sidebar which doesn't behave like a sidebar on mobile, yet the right-side gap is still there.

**Comment by jnicholCU** [comment]
Also the column sizes didn't match the column sizes of layout builder

**Comment by jnicholCU** [comment]
Wasn't actually related to missing the `ucb-contained-row` class. The `g-0` needed to be stripped and a class for sidebar containers needed to be added with a gutter of 0.
The nested rows in rows of sidebar content caused extra padding which broke the horizontal sidebar. Also it was not vertically aligned so that was another problem.
