### ISSUE TITLE
Video Reveal blocks don't reveal and play video when play button is clicked.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1250]
Something changed with the video reveal blocks where clicking the play icon doesn't reveal and play the video. There is no javascript error associated with this in the console.

Here's some examples:

https://www.colorado.edu/aerospace/admissions
https://www.colorado.edu/aerospace/about-us
https://www.colorado.edu/demos/documentation/block-content/video-reveal-block

**Comment by jnicholCU** [comment]
So there is something going on with youtube where sometimes embeded videos work and sometimes they don't and it's completely random as far as we can tell.

It's worked differently across all browsers and users on our team. It'll sometimes work in firefox and sometimes work in chrome, but then the next day it won't work at all. 

Vimeo has been consistent but we still haven't figured out if there is something on our end that we can do or not.

**Comment by kevincrafts** [comment]
Adding another example on here - all of these consistently do NOT work for me.

https://www.colorado.edu/ova/about-ova

**Comment by jnicholCU** [comment]
This is tied to our GTM tracking causing issues for the youtube videos specifically.
We talked to David today so he's going to double check the trackers and see if any of those could be breaking it.
As a partial "fix" but not really, we have updated the trackers to only work on Anonymous users. So logged in editors will see these videos working now since the GTM trakcers won't be triggering. However it is still hit or miss if they will work for normal users. This decision was made to account for admin interface controls being broken by the GTM tracking as well.
It is covered in this PR https://github.com/CuBoulder/tiamat10-profile/pull/199

**Comment by jnicholCU** [comment]
Hopefully we'll have fix coverage for the Anonymous users soon. Will wait for an update from David if he comes across anything that might be breaking the youtube videos specifically.

**Comment by kevincrafts** [comment]
Are there any updates on this issue?

**Comment by jnicholCU** [comment]
I've found what is causing all the youtube videos to break. 
I have a fix I can implement but I want to make sure there aren't other implications.
Hopefully have things sorted out EOD.

**Comment by jnicholCU** [comment]
There still seems to be some randomness to when the change in PR #1364 work or not...

**Comment by jnicholCU** [comment]
Via David:

> Within our GA4 stream there is an enhanced measurement section which collects a set of standard events, one of with is video engagement and specifically calls out Youtubes API. Turned it off and ta-da. Didn't occur to me until you mentioned the enhanced tracking protections and that dropped the idea to look at within GA4 since GTM didn't seem to be the problem.

Previewing image Screenshot 2024-10-08 at 2.18.29 PM.png
