### ISSUE TITLE
Newsletter user feedback

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1254]
I received some feedback and issues from one of our users today regarding newsletters so wanted to pass it along...

I've put together a number newsletters since the launch of D10 and have run into some problems I wanted to flag.

These newsletters are being done in D10 and the code is being pasted into a blank Marketing Cloud email.

These items are shown in the newsletter below:

1. Newsletters are limited to 600 px wide in the preview window but when sent through Marketing Cloud and opened in Windows Outlook, are always the full width of the window, breaking formatting.

2. The CU Boulder lockup at the top of newsletters is extremely large in Outlook but very tiny when the same newsletter is opened on an iPhone.

3. Articles added to newsletters are showing "&nbsp;" as plain text in strange places that do not appear in the original articles.

4. Newsletter text appears as Arial in the preview window, but are Times New Roman when opened on Outlook.

5. Background colors are not coming through. Newsletter BGs outside the header are all white.

6. The horizontal rules separating sections appear in the preview window but are missing when pasted to Marketing Cloud.

7. There are very large gaps between sections when you paste the code into Marketing Cloud.

8. Footer Social media link images appear to be broken.

These are issues I've run into with the editor:

1. There's a problem with saving. If I add text to a newsletter in the Edit view and then go directly to Preview, all changes are properly shown. However, if I close the window from there, the text is not saved despite appearing to be. You must go back to the content editor first and click Save before closing the window.

2. I'm having an intermittent problem where some images copied from D7 will not appear in the newsletter. If I try to add them, they show up in the edit view but are missing when I click save. This only applies to content manually created in newsletters, not newsletters comprised solely of articles with thumbnail images.

3. I'm having an intermittent problem where some sections show up fine in Edit but do not appear in the Preview if they don't have a Title.

**Comment by patrickbrown-io** [comment]
### Visual Issues

#### Major
- [ ] Articles added to newsletters are showing " " as plain text in strange places that do not appear in the original articles.
- [ ] Newsletters are limited to 600 px wide in the preview window but when sent through Marketing Cloud and opened in Windows Outlook, are always the full width of the window, breaking formatting.
- [ ] Background colors are not coming through. Newsletter BGs outside the header are all white.
- [ ] Footer Social media link images appear to be broken.

#### Minor
- [ ] The CU Boulder lockup at the top of newsletters is extremely large in Outlook but very tiny when the same newsletter is opened on an iPhone.

- [ ] Newsletter text appears as Arial in the preview window, but are Times New Roman when opened on Outlook. (Should have CSS to prevent this already, test in Email on Acid)

- [ ] The horizontal rules separating sections appear in the preview window but are missing when pasted to Marketing Cloud. (Check in email on acid)

- [ ] There are very large gaps between sections when you paste the code into Marketing Cloud.

### Editor Issues

- [ ] There's a problem with saving. If I add text to a newsletter in the Edit view and then go directly to Preview, all changes are properly shown. However, if I close the window from there, the text is not saved despite appearing to be. You must go back to the content editor first and click Save before closing the window.

- [ ] I'm having an intermittent problem where some images copied from D7 will not appear in the newsletter. If I try to add them, they show up in the edit view but are missing when I click save. This only applies to content manually created in newsletters, not newsletters comprised solely of articles with thumbnail images. 

- [ ] I'm having an intermittent problem where some sections show up fine in Edit but do not appear in the Preview if they don't have a Title. **(This was fixed in a recent update)**
