### ISSUE TITLE
New : Version Number to be displayed on the User Nodes 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#1274]
Add in a Theme Variable to hold a string to represent the release version number.  

This will be updated when a new release is pulled.  

Add a visible string to the bottom of the User nodes to show `Web Express Version : {theme_version_number}`

**Comment by timurtripp** [comment]
If we want this done automatically on GitHub, there are a few different ways it can be done but they all have different considerations.

My first thought was to write to a text file as part of the GitHub Workflow, have the `boulder_base.theme` read the file and expose the contents as a variable to the user page, but ideally we would be caching this rather than reading the file every time someone loads the user page. Then again, only logged-in users actually get access to the user page...

I'll roll with the text file solution for now. It's easiest to apply and doesn't have to be specific to the theme (other repos can get the file written they just won't do anything with it).

**Comment by timurtripp** [comment]
Unless there's anything I'm missing that Mike or Alan has come up with to do this.
