### ISSUE TITLE
Special characters not displaying properly in article grid block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1386]
Ampersands and non-breaking spaces are not rendering correctly when viewed in article summaries shown in the article grid block.

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/add4108f-a6df-4055-8cdd-a69a1870e5fb">

Example (In the spotlight section): https://www.colorado.edu/frenchitalian/

**Comment by patrickbrown-io** [comment]
Related to #1351

**Comment by kevincrafts** [comment]
This is also showing in article feature blocks - https://www.colorado.edu/aerospace/

<img width="1382" alt="image" src="https://github.com/user-attachments/assets/85a99247-acd8-4bcf-8efb-ef3c19b64300">

**Comment by patrickbrown-io** [comment]
All the Article aggregators use the same method for generating a missing summary using the Article body. I have a fix for this working on all the Article blocks but not yet on the Article List page - due to a major PR for Article List page currently in review, https://github.com/CuBoulder/tiamat-theme/pull/1387 .

Once that's through, the change to fix the Article List page can be made and this can be resolved quickly.
