### ISSUE TITLE
Inconsistent Breadcrumbs

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1401]
I'm not sure if this is related to some of the other breadcrumb issues we're tracking, so I'm adding this just in case...

This page (https://www.colorado.edu/artsandsciences/about-us/our-people/professors-distinction) shows a different set of breadcrumbs than this page (https://www.colorado.edu/artsandsciences/discover/our-people/teaching-professors-distinction) even though they are in the same path structure/hierarchy.

The first shows:
[Home](https://www.colorado.edu/artsandsciences/)  > [About the College of Arts and Sciences](https://www.colorado.edu/artsandsciences/about-us)  > Professors of Distinction
The second shows:
[Home](https://www.colorado.edu/artsandsciences/)  > [Our People](https://www.colorado.edu/artsandsciences/discover/our-people)  > Teaching Professors of Distinction

**Comment by jnicholCU** [comment]
Yeah, this is related to the other ticket.
They're different because of the aliases being different and breadcrumbs are based off aliases rather than menu structure.

<img width="392" alt="image" src="https://github.com/user-attachments/assets/93b62a20-90f7-4336-8863-8948cfe98914">

<img width="402" alt="image" src="https://github.com/user-attachments/assets/baedcae2-09bd-4c7c-9896-e04395342628">

**Comment by jnicholCU** [comment]
Duplicate #1344

**Comment by jnicholCU** [comment]
Just as a general update. This will most likely need custom development time as the contrib modules either don't do what we need, are heavier than we need, or aren't in a proper release. `menu_breadcrumb` works but it is still alpha and hasn't been updated in 2 years.

**Comment by jnicholCU** [comment]
Adding to list of topics to discuss at our Thursday team meeting

**Comment by jnicholCU** [comment]
Backlogging for now
