### ISSUE TITLE
Lots of space around newsletter title & date

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1510]
There looks to be a lot of extra space in the newsletter header

![image](https://github.com/user-attachments/assets/b167a9cc-bc7d-4a87-8eae-a1616e3dd4e9)

<img width="826" alt="image" src="https://github.com/user-attachments/assets/5b398acc-87aa-4c5f-9a96-5f989f2fd579">

**Comment by patrickbrown-io** [comment]
This was due to optional fields like the Intro Text and Intro image missing in this case, which still generated empty elements with default stylings. Additionally,  this particular style had extra padding it didn't need.

 I've added some intro text/image checks which should help prevent empty elements as well as removed the extra padding we removed everywhere else
