### ISSUE TITLE
Newsletter feature thumbnail  image appears too small

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1514]
When viewed on a mobile device (iPhone), the thumbnail image of feature articles is too small and is not scaling to fill the space.

![IMG_6C7B3C85C3DA-1](https://github.com/user-attachments/assets/cb628578-c534-4a11-ba68-73621af9d275)

**Comment by patrickbrown-io** [comment]
This is an iphone specific issue, it appears that it just gives all images the same width even with some additional css from the last update -- so teaser get bigger and features get smaller. 

Related to #1515

**Comment by patrickbrown-io** [comment]
@jnicholCU -- Tagged you so we can test fixes (I do not have an iPhone). Everything looks fine in Email on Acid iOS previews, which is frustrating.

If you want to try branch `issue/1507` I've added some additional CSS to try to lock this down. The images won't come though so you might need to find and replace the img src's with a proper image when testing since localhost wont work.

**Comment by jnicholCU** [comment]
Oooooh I gotta install the base mail app gross. 
I'll check this out and ping ya when I have a result.

**Comment by jnicholCU** [comment]
Looks like your change fixed the scaling issue, Pat.

![IMG_2748](https://github.com/user-attachments/assets/1b7e766a-db52-4e1f-8fd9-95499ec427b6)
