### ISSUE TITLE
Related articles on CUBT showing old and unrelated content

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1526]
The related articles on CUBT keeps showing the same two outdated and unrelated articles:

Examples:
https://www.colorado.edu/today/2024/12/02/finances-mess-your-shopping-mentality-might-be-problem
https://www.colorado.edu/today/2024/12/03/countdown-ice-free-arctic-new-research-warns-accelerated-timelines
https://www.colorado.edu/today/2024/11/19/dont-miss-pulitzer-prize-winning-journalist-bestselling-author-isabel-wilkerson-jan-16

The articles being included:
https://www.colorado.edu/today/2016/03/30/app-evening-sessions-among-new-features-cu-boulders-conference-world-affairs
https://www.colorado.edu/today/2016/03/30/sommers-bausch-observatory-hold-messier-marathon-stargazing-event-april-1

**Comment by patrickbrown-io** [comment]
I believe I've identified the problem, this is due to the number of Articles present on the CUBT site and the Related Articles isn't fetching all, just the first 50 or so returned from the call.  So the most related articles are buried in what should be later calls and the block finds the most related out of the first returned, which happens to be these older Articles.  

I think I'll use this as an opportunity to re-write the Related Articles block following our other web components, should be better at handling a large number of Articles like CUBT has. The Related Articles was a very early constructed block and we've learned a lot since then.
