### ISSUE TITLE
Javascript Includes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#165]
While we have prevented site editors from adding their own javascript to sites, there are a few services that we have allowed through various tools we made over the years. The most current way to do this is with the cu_js_includes module (https://github.com/CuBoulder/express_mono/tree/dev/modules/custom/cu_js_includes) which allows editors to create specific types of includes, and then add them to the pages they need via the context module (in cases were the javascript just needs to be added to the html), or a block (for when the javascript needs to be added to a particular region on the page).

The types of javascript includes we currently allow through this are:

AdmitHub, LiveChat, Slate forms, and StatusPage.

Sites may need more than one of each type of these per site and need the ability to place them on one, multiple, or all pages.

**Comment by AlanBCole** [comment]
I see that Kevin linked to the cu_js_includes module in one of our github repos. However, use the Express code found in our upstream repo here: https://github.com/CuBoulder/pantheon-upstream-express-production/tree/master/web/profiles/express/modules/custom/cu_js_include

Here are some things from the D7 codebase that might be of some help for learning how this feature works at the moment:

- I wrote this documentation at some point:
    - https://github.com/CuBoulder/pantheon-upstream-express-production/blob/master/web/profiles/express/modules/custom/cu_js_includes/README.md
- When the cu_js_includes module is enabled it adds a tab to the add content page (circled red)

![Image](https://user-images.githubusercontent.com/23508839/205091255-4a7d982c-fc03-411c-9f86-cb073b2fe4d1.png)

- A view of the includes tab:

![Image](https://user-images.githubusercontent.com/23508839/205098346-120e029b-0777-43f6-b9d1-629079cbcfc0.png)

- After clicking 'Add Includes':

![Image](https://user-images.githubusercontent.com/23508839/205098719-40c4aaa7-11f8-4221-aea3-592f332b228f.png)

- An example of a form for entering in the details for an include:

![Image](https://user-images.githubusercontent.com/23508839/205100386-f0d6e93e-d787-47e9-8467-03c578414474.png)

**Comment by AlanBCole** [comment]
Here are some other screen shots of include forms. These are the add include forms. The form included above is from the edit an existing include. You can see that the only difference is the delete button. The the admithub include just requires two ids in order to work correctly while the others require only one.


![Image](https://user-images.githubusercontent.com/23508839/205103995-41643874-8b4c-4b24-823b-8bcddce432c1.png)

![Image](https://user-images.githubusercontent.com/23508839/205103996-390d3dfe-bcda-4f2d-ab70-ac0a65156bf7.png)

![Image](https://user-images.githubusercontent.com/23508839/205103994-87486b18-6f56-4219-b66a-b0cfd87a82b9.png)
