### ISSUE TITLE
Hero Block Rendering

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#301]
I placed a hero block in the main content region, however the size options are not working, and the block spans the width of the browser rather than being limited to the region it is placed in:
![image](https://user-images.githubusercontent.com/349713/229613634-87126e2b-4519-4120-b6f8-48c96a29d475.png)

When I placed a block in the sidebar, the hero block stopped going across the entire page, however, it was not aligned properly with the other content in the region:
![image](https://user-images.githubusercontent.com/349713/229614259-6c1ad6ed-e3bb-401f-b6e9-a305837a812b.png)

**Comment by jnicholCU** [comment]
The block layout is creating a different set of html classes that differ from the way layout builder labels inline-blocks. 
While both still use the same Twig template, the styles end up breaking because of the different classes applied to each area. 
Will probably need to reevaluate class names and apply css that will work globally for these different areas.
