### ISSUE TITLE
Expandable Content needs the ability to reference/embed other custom blocks

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#335]
The expandable sections should have the ability to reference and embed other custom blocks that have been created. For example: https://www.colorado.edu/resources#academic_support-4225 has an expandable block that contains a collection grid block on each tab.

Other requirements:

- It should also be possible to have text and a custom block reference, however the text should always come first, followed by the custom block
- It should be possible to reference multiple custom blocks in the same tab/accordion item
- There should be an option to hide block titles since they may not be needed in this display. Note that this is different than the Display Title toggle when configuring a block as this block may be displayed elsewhere on the site and still need to display the title.

Screenshot of D7 Express Expandable edit screen:
![image](https://user-images.githubusercontent.com/349713/233495076-50d2b4b7-8d63-4032-a7b5-977cff2988fa.png)

**Comment by jnicholCU** [comment]
While working on this ran into templates not being using the same naming scheme when referencing other blocks
Will need to determine best way to include or extend templates already made so that styling works across the board
This will be extremely relevant when the reusable content patch is fully integrated into Layout Builder

Image below for context of what is displaying differently when referenced in an expandable content block
<img width="480" alt="image" src="https://user-images.githubusercontent.com/94021017/236260682-7873821d-9dd9-445d-a9cc-bcc6e3c2346a.png">

**Comment by jcsparks** [comment]
This will probably come up again, but at this point we've decided that we're not going to support nesting blocks.
