### ISSUE TITLE
Article List display issues

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#497]
While working on some article examples I came across the following issues with article list blocks:

**Article summaries not displaying in teaser view**
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/29ceff9d-3f26-433f-b382-24b049d70697)

**Article thumbnails not aligned with other content**
This happens when an article list block in places in a single column section - does not happen when block is placed in a multi-column section, however I'm not sure if this is because of the next issue.
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/e15569fb-8c17-45af-bd48-4ef683f1d592)
Multi-column section example:
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/46f98505-fd4c-4f6b-827a-7fe185f131f3)

**When an article block is placed in anything else but a full width column, the thumbnail moves above the content instead of remaining on the side**
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/a153af10-649a-4603-9338-bad0ee55cb06)

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/a8fd2749-a96c-4995-beb1-5716825804b1)

**Article borders should be 1px**
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/08985886-db80-48d1-80d0-d4538b7ea4e4)

**When viewed on a mobile device, thumbnails move above content**
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/c8ef702a-002d-4d5e-8caf-6f0ac1fd57a5)

**Thumbnails in the teaser view should be 100px square. Thumbnails in titles + thumbnails view should be 65px square**
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/1d35bc6c-273b-46db-825f-993da26d3ba5)

D7 example:
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/34a4e3de-ccd8-4d31-b3fd-c86a6ede8f45)

**When viewed on a mobile device thumbnails should be 50px square**
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/4e2c8563-0d84-48a1-98a5-3aed2d1b2aaa)

**Thumbnails in an article list set to display thumbnails and titles do not need a bottom margin on the thumbnail so space between border lines should be equal**
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/ca74c070-a31b-45b3-8a7e-655c5ea2919c)

**More articles link design**
Rather than being a button, the link to more articles should be a smaller link aligned to the right of the block. The button design should be used on the Article Grid and Article Feature blocks.
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/0dc08095-5142-4bd6-9933-cd96a7da9161)

D7 example of Article Grid and Article Feature blocks:
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/5944eaf2-fce3-4abe-b0f4-49b1bf23b565)

![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/56cb1e9d-d5ac-4e21-8a42-ce3d154f589a)

D7 example:
![image](https://github.com/CuBoulder/tiamat-theme/assets/349713/28e5caf7-c6c9-416f-819e-a0cf23cf0436)

**Comment by patrickbrown-io** [comment]
All Displays
- [ ] When an article block is placed in anything else but a full width column, the thumbnail moves above the content instead of remaining on the side
- [ ] Article thumbnails not aligned with other content (related to above)
- [ ] Article borders should be 1px
- [ ] When viewed on a mobile device thumbnails should be 50px square

Teaser Display
- [ ] Teaser thumbnails = 100px, 
- [ ] Article summaries not displaying in teaser view

Thumbnail & Title Displays
- [ ] Thumbnails do not need a bottom margin on the thumbnail, so space between border lines should be equal
- [ ] Title & Thumbnail imgs = 65px
- [ ] More articles link design, not a button. 
- [ ] Thumbnails in an article list set to display thumbnails and titles do not need a bottom margin on the thumbnail so space between border lines should be equal
