### ISSUE TITLE
Heading styles in editor

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#520]
The heading styling is looking good when rendered, but a questions was asked I we could bold ALL of the headings in the editor view, with the concern that a user might pick an incorrect heading because they want it to be bold:

<img width="1186" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/3b621df5-624e-41c0-86c0-ce04f6fdb866">

H2 and H3 are just a normal weight in the editor.

**Comment by patrickbrown-io** [comment]
All the headings seem to be bold. This might have been a Gin style but with Claro, this issue seems to be resolved. Closing this issue

<img width="907" alt="Screenshot 2024-02-02 at 2 57 42 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/85851903/e92a9263-64c1-4a98-b0c9-695f1c15864a">

<img width="407" alt="Screenshot 2024-02-02 at 2 58 42 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/85851903/88a14c2c-b3c9-4556-97e5-67fd78f9970b">
