### ISSUE TITLE
Article List Page : Hierarchical Taxonomy Filtering 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat-theme#696]
During the migration we noticed that sometimes there are sites that have hierarchical tags and/or category vocabularies for their article taxonomies.  

E.G. 
- Spotlight 
  - Spotlight Sudents
  - Spotlight Factulty
  - Spotlight Staff 

I'm suspecting that the Article List is expected to pull in the children elements if the parent term is selected as include filter.  We'll need to verify that would be the correct desired behavior here and determine if that's even possible with JSON:API tools we have.  

Leaving as an open question for the moment.

**Comment by patrickbrown-io** [comment]
After some experimenting, this gets bogged down with additional API calls quickly with our current implementation and JSON API's restrictions. This was tested with a dozen or so nested terms and had significant performance impacts on load.

This change would affect Article List page, Article List Blocks (such as Article Grid, Slider, Feature, etc) , the People List page, People List Block.

Possible solutions all involve major re-writes to JSON API Nodes and Blocks:
- Continue using JSON API, refactor the content types. Given term ids, check for children terms for additional ids, and then check those... and so on until no children. Use these lists of term ids to construct the API call in client-side JS (rather than Twig) and then hit the endpoint, then exclude as normal...but would still add an uncertain amount of calls for each term if terms are deeply nested, like a grandchild term (or even deeper). No way to change form checked/unchecked values (one way street).
- GraphQL -- Pros: Could make one nice call with include and exclusions, removes a lot of the JS logic. Maintain API approach for site to site communication. However this would involve a lot of new setup and refactoring, although it makes the work lighter on the Content Types.
- Module solution -- Would involve starting from scratch, not sure what this would entail. Think this would remove the future ability to share content site to site via API
- Form Side Module solution -- child terms get nicely positioned in the form like so by default, with hyphens:
```
          Parent term
             - Child Term
             - Child Term
                -- Grandchild Term
``` 
Use client side JS so when Parent term is checked, cascade those checks to all children and their children. However this doesn't affect migrated sites and they would need to re-check terms.

**Comment by jcsparks** [comment]
JSON:API doesn't work with heirarchical taxonomies.
