### ISSUE TITLE
Blocks placed in Above Content region via block layout should be aligned with other content in the region

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#819]
When a block is placed in the above content region, the block gets aligned to the left edge of the page rather than being placed in the center and aligned with the other content on the page. This leaves a blank space on the right side of the page:

<img width="1748" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/23f1bdad-02b7-4fb8-9a6b-5fb024053a54">

Looks like this is also due to the icon block styles getting applied at the block level instead of on the icon:
<img width="1745" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/d875be7d-1e94-48bc-a136-f8465484d9f0">

**Comment by jnicholCU** [comment]
The actual problem is that above and below content aren't containers so the content is left aligning automatically.
I guess the question is do we want those regions to be "contained" which I think the answer is probably yes(?) unless that is meant for full width hero units that are on every single page which sounds like a bad idea.
@jcsparks what do you think?
