### ISSUE TITLE
Error message upon logging out of admin side

### ISSUE THREAD

**Issue by nicolewaldrip** [CuBoulder/tiamat-theme#924]
When I try to log out of my sandbox, I receive this error message:
<img width="528" alt="Screenshot 2024-05-02 at 9 54 31 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/159831859/f587c1f8-9fc7-4d3a-a62a-587845162d57">

I would expect to either see a message letting me know that I've successfully logged out, or a return to the site in the logged out state.

**Comment by jcsparks** [comment]
This is a known issue.  I believe it's a problem it's an issue with FedAuth that we have in D7 as well.  In D7 when you click log-out nothing happens.  Not sure what we can do to fix this one and keep SSO working as well.

**Comment by nicolewaldrip** [comment]
I did compare to D7, and there it just returns to you the site in the logged out state vs. giving an error message, so that's what I wrote that as my expectation.

**Comment by jcsparks** [comment]
It doesn't actually log you out in D7.  Or rather, it attempts to, but because of Single-Sign On you get immediately logged back in.  I'd argue that's worse because you click the button and may not notice that you didn't actually get logged out.  

The "correct" way for this to work would be for FedAuth to implement the global sign-out functionality but I think that would be confusing to people as well because when they click "sign-out" in Web Express I don't think they actually mean ... and the portal and everywhere else that I'm currently logged in.  Which is how SSO works.
