### ISSUE TITLE
Unable to replace media

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#994]
I'm having some weird errors today on the site. This is another one I hadn't seen before. I need to change an image in the content grid. I've tried multiple times and get the same error. I wanted to log out and log back in to see if that helped but unable to do so (see my other ticket about logging out issues). 

https://live-ucbdev-homepage.pantheonsite.io/academics/grad-electrical-engineering

Go to layout and configure content grid on page.
![Screenshot 2024-05-21 at 9 29 56 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/5a952336-fa39-493f-b1db-f7f4d9d73031)

![Screenshot 2024-05-21 at 9 30 17 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/5d319a71-bf5b-4788-9e5b-5478db36066e)

Go to first image and remove.
![Screenshot 2024-05-21 at 9 30 28 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/4b23b93c-9e6b-4fb3-b6c4-e1bf5032239d)

![Screenshot 2024-05-21 at 9 30 35 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/0a23b31e-e444-490a-a4ef-f42e4f99ba76)

Click add media and get this:
![Screenshot 2024-05-21 at 9 29 39 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/6b711632-eef9-4c53-803f-6885a4242c5c)

**Comment by wturnbull** [comment]
One more thing to note on this - I selected an image in the media library and it inserted the wrong image (this is the clear caching issue). Normally I will have Joshua clear cache and then insert the correct image. This one I let it insert the incorrect image and saved. I was trying to fix the wrong image after Joshua cleared cache and experienced this error.

**Comment by wturnbull** [comment]
Just discovered it doesn't matter if there was a caching issue. Can't replace any images in the content grid. Get the same error.

**Comment by wturnbull** [comment]
Turns out it's not just replacing an image that isn't working. It includes trying to add an image into the content after saving it. (and not just trying to replace an image).

**Comment by jnicholCU** [comment]
This is an error specific to Safari. However we haven't been able to consistently replicate it outside of the Homepage sandbox. The browser is repositioning the page view to be at the very bottom in most cases so the user isn't able to see or scroll to the modal popup. As Wendy has noted, it happens when selecting the `Add Media` button on a block that has already been saved to the layout builder.

Wendy has the problem on version 17.3.1
I can recreate it in my dev environment as well as the homepage sandbox on version 17.5
But Kevin does not have the problem in 17.4.1
